### ISSUE TITLE
Cannot find module genutils

### ISSUE THREAD

**Issue by TakashiKoyama** [KiddLab/pacbio-vector-trim#1]
Dear Sir,

Hello, I first would like to appreciate you to distribute such a excellent script. This is what I want!
I am quite new for python and this might be stupid question. But please let me ask.

The script require h5py and genutils modules. I installed h5py but could not find genutils.

```
$ pip install genutils
Collecting genutils
/usr/local/pyenv/versions/2.7.8/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Could not find a version that satisfies the requirement genutils (from versions: )
No matching distribution found for genutils
```

Could you tell me how can I find and use genutils module?

best,
Takashi

**Comment by jmkidd** [comment]
Hi,

genutils is an in-house collection of utilities we developed.  It is not really needed here anymore, so I updated the script to no longer require it.  This version should work for you now.  Thanks!
